name: unittest

on: 
  push:
    branches:
      - master
  repository_dispatch:
    types: [build-images]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - variant: cpu
            python-version: 3.6
          - variant: cpu
            python-version: 3.7
          - variant: gpu
            python-version: 3.6

    steps:
      - uses: actions/checkout@v2

      - name: Login to the docker hub
        run: |
          docker login -u "${{ secrets.docker_user }}" -p "${{ secrets.docker_password }}"

      - name: Build the docker file
        run: |
          export DOCKER="sudo docker"
          export VARIANT="${{ matrix.variant }}"
          export PYTHON_VERSION="${{ matrix.python-version }}"
          ./build.sh
